# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Time to blog'
tagline:          'Must be advent'
description:      ''
url:              https://github.com/jschiefer/jschiefer.github.io
baseurl:          /

author:
  name:           'Hamstr'
  url:            

paginate:         5

github:
  repo:           https://github.com/jschiefer/jschiefer.github.io
